#1)pandas  

- pandas is python library or package
- it is used to analyze the data
- it is a data manipulation package in python for tabular data
- all data is in the form of rows and columns also known as dataframe
- we can think of data frame as an excel sheet because it have rows and columns

#2)uses of pandas

- it is used to import datasets from database,spreadsheets,comma-seperated values(CSV) files and more
- it can clean datasets for example,dealing with missing values(nul values)

divide into parts for understanding

- 1)load the data and analyze the data
- 2)identify the null values and clean the null values

In [ ]:
#install pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
#importing pandas

import pandas as pd

importing data files

In [ ]:
#import csv file
import pandas as pd
df = pd.read_csv(r"//content/sample_data/customers-100.csv")
print(df)

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]

In [ ]:
#import text file
import pandas as pd
df = pd.read_csv(r"/content/sample_data/DWSample3-TXT.txt",sep = "\s")
print(df)

  mynameismanikanta
0     andiamfromvzm

<ipython-input-56-e3e9847f6f55>:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv(r"/content/sample_data/DWSample3-TXT.txt",sep = "\s")

In [ ]:
#import excelfile(singlesheet)

import pandas as pd
df = pd.read_excel(r"/content/sample_data/file_example_XLS_50.xls")
print(df)

     0 First Name   Last Name  Gender        Country  Age        Date    Id
0    1      Dulce       Abril  Female  United States   32  15/10/2017  1562
1    2       Mara   Hashimoto  Female  Great Britain   25  16/08/2016  1582
2    3     Philip        Gent    Male         France   36  21/05/2015  2587
3    4   Kathleen      Hanner  Female  United States   25  15/10/2017  3549
4    5    Nereida     Magwood  Female  United States   58  16/08/2016  2468
5    6     Gaston       Brumm    Male  United States   24  21/05/2015  2554
6    7       Etta        Hurn  Female  Great Britain   56  15/10/2017  3598
7    8    Earlean      Melgar  Female  United States   27  16/08/2016  2456
8    9   Vincenza     Weiland  Female  United States   40  21/05/2015  6548
9   10     Fallon     Winward  Female  Great Britain   28  16/08/2016  5486
10  11    Arcelia      Bouska  Female  Great Britain   39  21/05/2015  1258
11  12   Franklyn      Unknow    Male         France   38  15/10/2017  2579
12  13    Sherron    Ascencio  Female  Great Britain   32  16/08/2016  3256
13  14     Marcel   Zabriskie    Male  Great Britain   26  21/05/2015  2587
14  15       Kina    Hazelton  Female  Great Britain   31  16/08/2016  3259
15  16   Shavonne         Pia  Female         France   24  21/05/2015  1546
16  17     Shavon      Benito  Female         France   39  15/10/2017  3579
17  18   Lauralee     Perrine  Female  Great Britain   28  16/08/2016  6597
18  19     Loreta      Curren  Female         France   26  21/05/2015  9654
19  20     Teresa      Strawn  Female         France   46  21/05/2015  3569
20  21    Belinda     Partain  Female  United States   37  15/10/2017  2564
21  22      Holly        Eudy  Female  United States   52  16/08/2016  8561
22  23       Many      Cuccia  Female  Great Britain   46  21/05/2015  5489
23  24     Libbie       Dalby  Female         France   42  21/05/2015  5489
24  25     Lester     Prothro    Male         France   21  15/10/2017  6574
25  26     Marvel        Hail  Female  Great Britain   28  16/08/2016  5555
26  27    Angelyn        Vong  Female  United States   29  21/05/2015  6125
27  28  Francesca   Beaudreau  Female         France   23  15/10/2017  5412
28  29      Garth       Gangi    Male  United States   41  16/08/2016  3256
29  30      Carla    Trumbull  Female  Great Britain   28  21/05/2015  3264
30  31       Veta       Muntz  Female  Great Britain   37  15/10/2017  4569
31  32     Stasia      Becker  Female  Great Britain   34  16/08/2016  7521
32  33       Jona     Grindle  Female  Great Britain   26  21/05/2015  6458
33  34      Judie    Claywell  Female         France   35  16/08/2016  7569
34  35     Dewitt      Borger    Male  United States   36  21/05/2015  8514
35  36       Nena      Hacker  Female  United States   29  15/10/2017  8563
36  37     Kelsie     Wachtel  Female         France   27  16/08/2016  8642
37  38        Sau        Pfau  Female  United States   25  21/05/2015  9536
38  39    Shanice   Mccrystal  Female  United States   36  21/05/2015  2567
39  40      Chase      Karner    Male  United States   37  15/10/2017  2154
40  41     Tommie   Underdahl    Male  United States   26  16/08/2016  3265
41  42     Dorcas      Darity  Female  United States   37  21/05/2015  8765
42  43      Angel       Sanor    Male         France   24  15/10/2017  3259
43  44  Willodean        Harn  Female  United States   39  16/08/2016  3567
44  45     Weston     Martina    Male  United States   26  21/05/2015  6540
45  46       Roma  Lafollette  Female  United States   34  15/10/2017  2654
46  47     Felisa        Cail  Female  United States   28  16/08/2016  6525
47  48   Demetria       Abbey  Female  United States   32  21/05/2015  3265
48  49     Jeromy        Danz    Male  United States   39  15/10/2017  3265
49  50   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125

In [ ]:
#import excel files(multiple sheets)
import pandas as pd
df = pd.read_excel(r"/content/sample_data/Orders-With Nulls.xlsx",sheet_name = 1)
print(df)

Empty DataFrame
Columns: []
Index: []

In [ ]:
#import json file
import pandas as pd
df = pd.read_json(r"/content/sample_data/anscombe.json")
print(df)

   Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

#viewing and understanding dataframes

- we can use two methods
- 1)head()
- 2)tail()

In [35]:
#using head
import pandas as pd
df = pd.read_csv(r"/content/sample_data/customers-100.csv")
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [ ]:
#using head specific records
import pandas as pd
df = pd.read_csv(r"/content/sample_data/customers-100.csv")
df.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [ ]:
#using tail()
import pandas as pd
df = pd.read_csv(r"/content/sample_data/customers-100.csv")
df.tail()   #gives last 5 records

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [ ]:
#using tail() specific records
import pandas as pd
df = pd.read_csv(r"/content/sample_data/customers-100.csv")
df.tail(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
90,91,5ef6d3eefdD43bE,Nina,Chavez,Byrd-Campbell,Cassidychester,Bhutan,053-344-3205,+1-330-920-5422x571,elliserica@frank.com,2020-03-26,https://www.pugh.com/
91,92,98b3aeDcC3B9FF3,Shane,Foley,Rocha-Hart,South Dannymouth,Hungary,+1-822-569-0302,001-626-114-5844x55073,nsteele@sparks.com,2021-07-06,https://www.holt-sparks.com/
92,93,aAb6AFc7AfD0fF3,Collin,Ayers,Lamb-Peterson,South Lonnie,Anguilla,404-645-5351x012,001-257-582-8850x8516,dudleyemily@gonzales.biz,2021-06-29,http://www.ruiz.com/
93,94,54B5B5Fe9F1B6C5,Sherry,Young,"Lee, Lucero and Johnson",Frankchester,Solomon Islands,158-687-1764,(438)375-6207x003,alan79@gates-mclaughlin.com,2021-04-04,https://travis.net/
94,95,BE91A0bdcA49Bbc,Darrell,Douglas,"Newton, Petersen and Mathis",Daisyborough,Mali,001-084-845-9524x1777,001-769-564-6303,grayjean@lowery-good.com,2022-02-17,https://banks.biz/
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

if we want how many rows and columns present in data we can use shape method

In [ ]:
import pandas as pd
df = pd.read_csv(r"/content/sample_data/customers-100.csv")
print(df.shape)     #returns rows and columns
print(df.shape[0])  #returns rows
print(df.shape[1])  #returns columns

(100, 12)
100
12

3) describe():

- it will provide the only nemeric columns in the dataframe

In [ ]:
import pandas as pd
df = pd.read_csv(r"/content/sample_data/customers-100.csv")
df.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

4)info():

- it will provide complete information about dataframe

In [ ]:
import pandas as pd
df = pd.read_csv(r"/content/sample_data/customers-100.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

columns:

- get only column names

In [ ]:
import pandas as pd
df = pd.read_csv("/content/sample_data/customers-100.csv")
df.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [ ]:
list(df.columns)

['Index',
 'Customer Id',
 'First Name',
 'Last Name',
 'Company',
 'City',
 'Country',
 'Phone 1',
 'Phone 2',
 'Email',
 'Subscription Date',
 'Website']

#checking missing letters or null values

- three types
- 1)isnull()
- 2)isnull.any()
  - it will returns null values present only in columns
-3)isnull.sum()
  - it will returns the value in numeric how many null values present in data frame

In [ ]:
#isnull()
import numpy as np
df = pd.read_csv("/content/sample_data/customers-100.csv")
df.isnull()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#isnull().any()
import pandas as pd
df = pd.read_csv("/content/sample_data/customers-100.csv")
df.isnull().any()

Index                False
Customer Id          False
First Name           False
Last Name            False
Company              False
City                 False
Country              False
Phone 1              False
Phone 2              False
Email                False
Subscription Date    False
Website              False
dtype: bool

In [ ]:
#isnull.sum()
import pandas as pd
df = pd.read_csv("/content/sample_data/customers-100.csv")
df.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

#slicing and extracting data in pandas

In [ ]:
#specific column using head(15)
import pandas as pd
df = pd.read_csv("/content/sample_data/customers-100.csv")
df["Customer Id"].head(15)

0     DD37Cf93aecA6Dc
1     1Ef7b82A4CAAD10
2     6F94879bDAfE5a6
3     5Cef8BFA16c5e3c
4     053d585Ab6b3159
5     2d08FB17EE273F4
6     EA4d384DfDbBf77
7     0e04AFde9f225dE
8     C2dE4dEEc489ae0
9     8C2811a503C7c5a
10    216E205d6eBb815
11    CEDec94deE6d69B
12    e35426EbDEceaFF
13    A08A8aF8BE9FaD4
14    6fEaA1b7cab7B6C
Name: Customer Id, dtype: object

In [ ]:
#multiple columns
import pandas as pd
df = pd.read_csv("/content/sample_data/customers-100.csv")
df[["Customer Id","City"]].head(8)

       Customer Id               City
0  DD37Cf93aecA6Dc       East Leonard
1  1Ef7b82A4CAAD10  East Jimmychester
2  6F94879bDAfE5a6      Isabelborough
3  5Cef8BFA16c5e3c         Bensonview
4  053d585Ab6b3159     West Priscilla
5  2d08FB17EE273F4      Chavezborough
6  EA4d384DfDbBf77           Lake Ana
7  0e04AFde9f225dE            Kimport

In [ ]:
#specific row
import pandas as pd
df =pd.read_csv("/content/sample_data/customers-100.csv")
df[df.index==4]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [ ]:
#multiple rows
import pandas as pd
df = pd.read_csv("/content/sample_data/customers-100.csv")
df[df.index.isin(range(5,9))]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/

#using loc(location) and iloc(integer location):

- by using this we can access particular rows

In [ ]:
import pandas as pd
df = pd.read_csv("/content/sample_data/customers-100.csv")
df.loc[5]

Index                                     6
Customer Id                 2d08FB17EE273F4
First Name                            Aimee
Last Name                             Downs
Company                        Steele Group
City                          Chavezborough
Country              Bosnia and Herzegovina
Phone 1                 (283)437-3886x88321
Phone 2                        999-728-1637
Email                   louis27@gilbert.com
Subscription Date                2020-02-25
Website              http://www.berger.net/
Name: 5, dtype: object

In [ ]:
import pandas as pd
df = pd.read_csv("/content/sample_data/customers-100.csv")
df.iloc[8:10]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

#convert data into array:

- it will completely works on 2-D array while in numerics

In [ ]:
import pandas as pd
df = pd.read_csv("/content/sample_data/titanic.csv")
df.to_numpy()

array([[0, 3, 'Braund, Mr. Owen Harris', ..., 7.25, 1, 0],
       [1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', ...,
        71.2833, 1, 0],
       [1, 3, 'Heikkinen, Miss. Laina', ..., 7.925, 0, 0],
       ...,
       [1, 1, 'Graham, Miss. Margaret Edith', ..., 30.0, 0, 0],
       [1, 1, 'Behr, Mr. Karl Howell', ..., 30.0, 0, 0],
       [0, 3, 'Dooley, Mr. Patrick', ..., 7.75, 0, 0]], dtype=object)

#clean the null values

- they are 3 types
-1)dropping missing values(dropna()):
  - it is the way to deal with missing data to drop it
  - dropna() is used for this method
  - we can using this method entire null data will loss

In [ ]:
import pandas as pd
data = pd.read_csv(r"/content/sample_data/Diabetes Missing Data.csv")
data.head(10)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,NaN,NaN,25.6,0.201,30,0
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
7,10,115.0,NaN,NaN,NaN,35.3,0.134,29,0
8,2,197.0,70.0,45.0,543.0,30.5,0.158,53,1
9,8,125.0,96.0,NaN,NaN,NaN,0.232,54,1

In [ ]:
#finding null values
data.isnull().sum()

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [ ]:
#shape
print(data.shape)
#using dropna method
data1 = data.dropna()
print(data1.isnull().sum())
data1.shape

(768, 9)
Pregnant             0
Glucose              0
Diastolic_BP         0
Skin_Fold            0
Serum_Insulin        0
BMI                  0
Diabetes_Pedigree    0
Age                  0
Class                0
dtype: int64

(392, 9)

In [ ]:
#using inplace method
import pandas as pd
data = pd.read_csv(r"/content/sample_data/Diabetes Missing Data.csv")
data.head()
print(data.shape)
data.dropna(inplace=True,axis = 0)
print(data.isnull().sum())
print(data.shape)

(768, 9)
Pregnant             0
Glucose              0
Diastolic_BP         0
Skin_Fold            0
Serum_Insulin        0
BMI                  0
Diabetes_Pedigree    0
Age                  0
Class                0
dtype: int64
(392, 9)

2)replacing missing values:

- we can replace the values with mean or median
- we can call it as impitation or replacement technique

In [47]:
import pandas as pd
data = pd.read_csv("/content/sample_data/Diabetes Missing Data.csv")
print(data.isnull().sum())
data.shape

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

(768, 9)

In [39]:
#replace null values using mean
mean_value = data.mean()
print(mean_value)
data1 = data.fillna(mean_value)
data1.head()

Pregnant               3.845052
Glucose              121.686763
Diastolic_BP          72.405184
Skin_Fold             29.153420
Serum_Insulin        155.548223
BMI                   32.457464
Diabetes_Pedigree      0.471876
Age                   33.240885
Class                  0.348958
dtype: float64

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.00000,155.548223,33.6,0.627,50,1
1,1,85.0,66.0,29.00000,155.548223,26.6,0.351,31,0
2,8,183.0,64.0,29.15342,155.548223,23.3,0.672,32,1
3,1,89.0,66.0,23.00000,94.000000,28.1,0.167,21,0
4,0,137.0,40.0,35.00000,168.000000,43.1,2.288,33,1

In [50]:
#using median
median_value = data.median()
data2 = data.fillna(median_value)
print(median_value)
print(data2.shape)
data2.head()

Pregnant               3.0000
Glucose              117.0000
Diastolic_BP          72.0000
Skin_Fold             29.0000
Serum_Insulin        125.0000
BMI                   32.3000
Diabetes_Pedigree      0.3725
Age                   29.0000
Class                  0.0000
dtype: float64
(768, 9)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1


3)duplicate data:

- it will drop the repeating values
- it will checks row by row if there is any repeated values it can drop

In [72]:
import pandas as pd
data = pd.read_csv("/content/sample_data/Diabetes Missing Data.csv")
print(data.isnull().sum())
print(data.shape)
data1 = data.drop_duplicates()
data1.shape

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64
(768, 9)

(768, 9)

#renaming columns(rename()):

- it will change the column name

In [81]:
import pandas as pd
data = pd.read_csv("/content/sample_data/Diabetes Missing Data.csv")
data.rename(columns = {"Age":"New_Age","BMI":"Bmi"},inplace=True)
data.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,Bmi,Diabetes_Pedigree,New_Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

#data analysis in pandas:

- it can counts the no of categories contain in values

In [86]:
import pandas as pd
data = pd.read_csv("/content/sample_data/Diabetes Missing Data.csv")
print(data["Class"].value_counts())
data["Pregnant"].value_counts()

Class
0    500
1    268
Name: count, dtype: int64

Pregnant
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: count, dtype: int64

#aggregating data with groupby() in pandas:

- it is used for summarizing the data aggregating function more than 2 columns
- aggregative known as sum and average
- when we apply groupby method we need to clean the data

In [105]:
import pandas as pd
data = pd.read_csv("/content/sample_data/Diabetes Missing Data.csv")
data.head()
#clean the data
median_value = data.median()
print(median_value)
data1 = data.fillna(median_value).head(20)
data1.head(20)
data1.isnull().sum()
data1.groupby("Glucose").median().head()

Pregnant               3.0000
Glucose              117.0000
Diastolic_BP          72.0000
Skin_Fold             29.0000
Serum_Insulin        125.0000
BMI                   32.3000
Diabetes_Pedigree      0.3725
Age                   29.0000
Class                  0.0000
dtype: float64

,Pregnant,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
Glucose,,,,,,,,
78.0,3.0,50.0,32.0,88.0,31.0,0.248,26.0,1.0
85.0,1.0,66.0,29.0,125.0,26.6,0.351,31.0,0.0
89.0,1.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
100.0,7.0,72.0,29.0,125.0,30.0,0.484,32.0,1.0
103.0,1.0,30.0,38.0,83.0,43.3,0.183,33.0,0.0